# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

dishes = [
  # { title: 'Aladdin', rating: 'G', release_date: '25-Nov-1992' },
  # { title: 'The Terminator', rating: 'R', release_date: '26-Oct-1984' },
  # { title: 'When Harry Met Sally', rating: 'R', release_date: '21-Jul-1989' },
  # { title: 'The Help', rating: 'PG-13', release_date: '10-Aug-2011' },
  # { title: 'Chocolat', rating: 'PG-13', release_date: '5-Jan-2001' },
  # { title: 'Amelie', rating: 'R', release_date: '25-Apr-2001' },
  # { title: '2001: A Space Odyssey', rating: 'G', release_date: '6-Apr-1968' },
  # { title: 'The Incredibles', rating: 'PG', release_date: '5-Nov-2004' },
  # { title: 'Raiders of the Lost Ark', rating: 'PG', release_date: '12-Jun-1981' },
  # { title: 'Chicken Run', rating: 'G', release_date: '21-Jun-2000' },
  { name: 'Roasted Pork Loin', hall: 'Ferris Booth Commons', property: 'normal', calories: 100 },
  { name: 'Oatmeal with Milk', hall: 'John Jay', property: 'gluten free, halal, vegan', calories: 120},
  { name: 'Yellow Rice', hall: 'John Jay', property: 'gluten free', calories: 140 },
  { name: 'Vegatable Medley', hall: 'Ferris Booth Commons', property: 'halal', calories: 60 },
  { name: 'Porl Sausage', hall: 'John Jay', property: 'gluten free', calories: 230 },
  { name: 'Beef Rendang', hall: 'John Jay', property: 'normal', calories: 320 },
  { name: 'Chipolet Roasted Chicken', hall: 'John Jay', property: 'normal', calories: 217 },
  { name: 'Black Beans', hall: 'John Jay', property: 'gluten free, halal, vegan', calories: 132 },
  { name: 'Roasted Butternut Squash', hall: 'John Jay', property: 'normal', calories: 171 },
  { name: 'Vegetable Roll', hall: 'John Jay', property: 'normal', calories: 193 },
  { name: 'Spaghetti', hall: 'John Jay', property: 'vegan, halal', calories: 221 },
  { name: 'Chicken Noodle Soup', hall: 'John Jay', property: 'normal', calories: 324 },
  { name: 'Mashed Sweet Potatoes', hall: 'John Jay', property: 'normal', calories: 209 },
  { name: 'Brussel Sprouts', hall: 'John Jay', property: 'gluten free, halal, vegan', calories: 36 },
  { name: 'Farrow w./ Sundried Tomatoes', hall: 'John Jay', property: 'normal', calories: 193 },
  { name: 'Caprese Grilled Cheese', hall: 'John Jay', property: 'normal', calories: 68 },
  { name: 'Minestrone Soup', hall: 'John Jay', property: 'normal', calories: 286 },
  { name: 'Meatball', hall: 'John Jay', property: 'normal', calories: 192 },
  { name: 'Marinara Sauce', hall: 'John Jay', property: 'gluten free, halal, vegan', calories: 121 },
  { name: 'Grain bowl', hall: 'John Jay', property: 'normal', calories: 220 },
  { name: 'Whole Wheat Penne', hall: 'John Jay', property: 'vegan', calories: 126 },
  { name: 'Jasmine Rice', hall: 'John Jay', property: 'gluten free, halal, vegan', calories: 83 },
  { name: 'Lemon Cilantro Rice', hall: 'John Jay', property: 'normal', calories: 64 },
  { name: 'Cannellini Beans', hall: 'John Jay', property: 'normal', calories: 98 },
  { name: 'Roasted Mushroom', hall: 'John Jay', property: 'vegan', calories: 103 },
  { name: 'Diced Potatoes', hall: 'John Jay', property: 'vegan', calories: 193 },
  { name: 'Scrambled Eggs', hall: 'John Jay', property: 'normal', calories: 284 },
  { name: 'JJ\'s Cheeseburger', hall: 'JJ', property: 'normal', calories: 483 },
  { name: 'JJ\'s Southwest Turkey Burger', hall: 'JJ', property: 'normal', calories: 533 },
  { name: 'JJ\'s Beyond Meat Burger', hall: 'JJ', property: 'normal', calories: 400 },
  { name: 'JJ\'s Grilled Chicken Sandwich', hall: 'JJ', property: 'normal', calories: 451 },
  { name: 'Poblano Burger', hall: 'JJ', property: 'normal', calories: 931 },
  { name: 'JJ\'s Prosciutto, Mozzarella, Tomato, & Pesto Mayo', hall: 'JJ', property: 'normal', calories: 791 },
  { name: 'JJ\'s Pot Roast Po Boy with Mayo & Pickles', hall: 'JJ', property: 'normal', calories: 839 },
  { name: 'JJ\'s Vegan Pineapple Pancakes with Coconut Glaze', hall: 'JJ', property: 'normal', calories: 621 },
  { name: 'JJ\'s Beyond Meat Burger', hall: 'JJ', property: 'normal', calories: 621 },
  { name: 'JJ\'s Vegan Pineapple Pancakes with Coconut Glaze', hall: 'JJ', property: 'normal', calories: 621 },
  { name: 'JJ\'s Hot Honey Popcorn Chicken Quesadilla', hall: 'JJ', property: 'normal', calories: 691 },
  { name: 'Black Bean Poblano Burger', hall: 'JJ', property: 'normal', calories: 872 },
  { name: 'JJ\'s Onion Rings', hall: 'JJ', property: 'normal', calories: 391 },
  { name: 'Chickend Tenders', hall: 'JJ', property: 'normal', calories: 480 },
  { name: 'JJ\'s Curly Fries', hall: 'JJ', property: 'normal', calories: 493 },
  { name: 'Cheese Blintz', hall: 'Ferris Booth Commons', property: 'vegetarian', calories: 328 },
  { name: 'Turkey Sausage', hall: 'Ferris Booth Commons', property: 'gluten free', calories: 346 },
  { name: 'Biscuits & Sausage Gravy', hall: 'Ferris Booth Commons', property: 'normal', calories: 412 },
  { name: 'Pork Sausage', hall: 'Ferris Booth Commons', property: 'gluten free', calories: 337 },
  { name: 'Tofu Sausage', hall: 'Ferris Booth Commons', property: 'gluten free, halal, vegan', calories: 159 },
  { name: 'Beyond Sausage', hall: 'Ferris Booth Commons', property: 'gluten free, halal, vegan', calories: 188 },
  { name: 'French Toast', hall: 'Ferris Booth Commons', property: 'vegetarian', calories: 244 },
  { name: 'O\'Brien Potatoes', hall: 'Ferris Booth Commons', property: 'normal', calories: 267 },
  { name: 'Scrambled Eggs', hall: 'Ferris Booth Commons', property: 'normal', calories: 187 },
  { name: 'Pork Bacon', hall: 'Ferris Booth Commons', property: 'normal', calories: 448 },
  { name: 'Oatmeal', hall: 'Ferris Booth Commons', property: 'normal', calories: 399 },
  { name: 'Meatball Sub', hall: 'Chef Mike\'s Sub Shop', property: 'normal', calories: 298 },
]

dishes.each do |dish|
  Dish.create!(dish)
end
